### ISSUE TITLE
history support?

### ISSUE THREAD

**Issue by kevin-jj** [shioyama/friendly_id-mobility#1]
Would you like to add history support? 

Thanks.

**Comment by shioyama** [comment]
I implemented this in #2, without any generators for adding the locale to the slugs table (for now). Could you try out the `history` branch and see if it works for you? I added a few specs and it seems to work (with very little code changes).

**Comment by shioyama** [comment]
I've released 0.3.0 with support for history, including a generator to add the locale column to the slugs table.
