### ISSUE TITLE
Support for Mobility 1.0

### ISSUE THREAD

**Issue by olimart** [shioyama/friendly_id-mobility#22]
Hi, Mobiilty gem release 1.0 is out and is currently locked in this gem.
`spec.add_dependency 'mobility',    '>= 0.5.1', '< 1.0'`

Not sure if this implies changes on this gem but can the dependency be relaxed? Thanks

**Comment by shioyama** [comment]
Yup, looking into it now :+1:

**Comment by olimart** [comment]
Thank you
