### ISSUE TITLE
Feature Request:  identity_cache compatibility

### ISSUE THREAD

**Issue by kevin-jj** [shioyama/friendly_id-mobility#6]
@shioyama   Kindly please add support for identity_cache in your part time.

The below code works out in Globalize, Friendly_id-globalize gem but it returns nil in friendly_id-mobility. Thanks advance.

## Identity_cache
```ruby
include IdentityCache
cache_index :slug, :unique => true

Model.fetch_by_slug(params[:slug]) 
```

**Comment by shioyama** [comment]
Sorry not really a priority.

**Comment by shioyama** [comment]
By the way, for Mobility you would have to use the `i18n` scope: `Model.i18n.fetch_by_slug(params[:slug])`. I don't know if it will work but it certainly won't work without the scope.

**Comment by shioyama** [comment]
Also, make sure you `extend Mobility` and call `translates` *before* including `IdentityCache`. For anything else, post a question to StackOverflow.

**Comment by kevin-jj** [comment]
IdentityCache::UnsupportedScopeError: IdentityCache doesn't support rails scopes.  @shioyama
